import { SystemHealth } from '@/types';

export const initialSystems: SystemHealth[] = [
  {
    id: 'sys-001',
    name: 'C2 PRIMARY',
    status: 'operational',
    cpu: 42,
    memory: 67,
    network: 850,
    uptime: 864000,
    lastHeartbeat: Date.now(),
  },
  {
    id: 'sys-002',
    name: 'SATCOM RELAY',
    status: 'operational',
    cpu: 28,
    memory: 45,
    network: 1200,
    uptime: 432000,
    lastHeartbeat: Date.now(),
  },
  {
    id: 'sys-003',
    name: 'ISR PROCESSOR',
    status: 'degraded',
    cpu: 89,
    memory: 91,
    network: 2100,
    uptime: 172800,
    lastHeartbeat: Date.now(),
  },
  {
    id: 'sys-004',
    name: 'RADAR ARRAY',
    status: 'operational',
    cpu: 55,
    memory: 63,
    network: 450,
    uptime: 604800,
    lastHeartbeat: Date.now(),
  },
  {
    id: 'sys-005',
    name: 'DATALINK HUB',
    status: 'operational',
    cpu: 35,
    memory: 52,
    network: 3200,
    uptime: 1296000,
    lastHeartbeat: Date.now(),
  },
  {
    id: 'sys-006',
    name: 'CRYPTO MODULE',
    status: 'operational',
    cpu: 18,
    memory: 30,
    network: 100,
    uptime: 2592000,
    lastHeartbeat: Date.now(),
  },
];
