import { Entity } from '@/types';

export const initialEntities: Entity[] = [
  {
    id: 'e-001',
    callsign: 'EAGLE-1',
    type: 'friendly',
    category: 'aircraft',
    position: { lat: 38.8951, lng: -77.0364 },
    heading: 45,
    speed: 420,
    altitude: 35000,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-002',
    callsign: 'VIPER-6',
    type: 'friendly',
    category: 'aircraft',
    position: { lat: 36.8529, lng: -75.9780 },
    heading: 120,
    speed: 380,
    altitude: 28000,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-003',
    callsign: 'SHADOW-3',
    type: 'friendly',
    category: 'drone',
    position: { lat: 34.0522, lng: -118.2437 },
    heading: 270,
    speed: 150,
    altitude: 18000,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-004',
    callsign: 'TITAN-12',
    type: 'friendly',
    category: 'vessel',
    position: { lat: 32.7157, lng: -117.1611 },
    heading: 180,
    speed: 22,
    altitude: 0,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-005',
    callsign: 'GHOST-7',
    type: 'friendly',
    category: 'ground-unit',
    position: { lat: 35.0527, lng: -78.8784 },
    heading: 0,
    speed: 0,
    altitude: 0,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-006',
    callsign: 'UNKNOWN-ALPHA',
    type: 'unknown',
    category: 'aircraft',
    position: { lat: 37.7749, lng: -72.4194 },
    heading: 260,
    speed: 510,
    altitude: 40000,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-007',
    callsign: 'NEUTRAL-TANGO',
    type: 'neutral',
    category: 'vessel',
    position: { lat: 30.2672, lng: -81.3997 },
    heading: 15,
    speed: 12,
    altitude: 0,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-008',
    callsign: 'HOSTILE-BRAVO',
    type: 'hostile',
    category: 'vessel',
    position: { lat: 25.7617, lng: -70.1918 },
    heading: 315,
    speed: 28,
    altitude: 0,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-009',
    callsign: 'SENTRY-4',
    type: 'friendly',
    category: 'satellite',
    position: { lat: 40.7128, lng: -74.0060 },
    heading: 90,
    speed: 0,
    altitude: 220000,
    lastUpdate: Date.now(),
    track: [],
  },
  {
    id: 'e-010',
    callsign: 'SPECTRE-2',
    type: 'friendly',
    category: 'drone',
    position: { lat: 33.4484, lng: -112.0740 },
    heading: 180,
    speed: 120,
    altitude: 12000,
    lastUpdate: Date.now(),
    track: [],
  },
];
